name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository (deep)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Checks in Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/kolint/kolint-devcontainer
          cacheFrom: ghcr.io/kolint/kolint-devcontainer
          push: always
          runCmd: pnpm run checks
